# Remove qualquer include residual que a imagem base tente injetar
include /dev/null;

events {
    worker_connections 1024;
}

http {
    # IMPORTANTE: Desativamos a leitura da pasta conf.d que continha o Welcome padrão
    # Isso garante que NADA vai sobrescrever as suas rotas abaixo

    upstream backend_servers {
        ip_hash;
        server collab-app-1:8080;
        server collab-app-2:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws {
            proxy_pass http://backend_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}